### ISSUE TITLE
[Meta] clarify policy around collaborator status for this repo

### ISSUE THREAD

**Issue by aspiers** [isaacs/github#1472]
Hi there,

I would like to know if there is a possibility to add other collaborators to this repo?  Yes, to be perfectly honest I am asking primarily for myself, since I have contributed quite a lot to this repo ([57 issues at the time of writing](https://github.com/isaacs/github/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+involves%3Aaspiers), of which [I submitted 27 myself](https://github.com/isaacs/github/issues?q=is%3Aissue+sort%3Aupdated-desc+involves%3Aaspiers+author%3Aaspiers)), but there's a limit to how much I can contribute without having collaborator access.  For example, I can't:

- Add or amend labels on issues
- Close issues which are resolved, unless I submitted them myself

However the question is not just for me: I'm sure there are other contributors out there who would be able to help make this repo even better if they had collaborator privileges.

I see from #430 and #459 that there has been some kind of process for adding collaborators in the past, but it would be nice if the policy around this was clarified, even if the policy is "we won't ever add any new collaborators, sorry".

Thanks for any clarification you can offer here!

**Comment by cirosantilli** [comment]
@isaacs hasn't replied in a while to at mentions, and no one else can add new people.

The only solution is a side channel contact with him, try email or the contact form on hist website or twitter.

For the record, i support adding @aspiers as a collaborator.

**Comment by aspiers** [comment]
Thanks a lot @cirosantilli. I'll see if I can reach @isaacs some other way.

**Comment by aspiers** [comment]
I just emailed @isaacs about this.

**Comment by aspiers** [comment]
@isaacs responded very quickly and has kindly made me and @TPS collaborators.  Since this issue was mainly about the policy / process around changing collaborator status, I'll leave  it open for now.

**Comment by TPS** [comment]
I did close #619, though -  that's specifically re: myself. :blush:

**Comment by TPS** [comment]
Also, is there anyplace there's a complete public list of collaborators, &/or a way to notify the whole group @isaacs/collaborators - style?  I'd like to open perhaps some meta-issues to hammer things out between us (e.g., labeling or comment policy), or have users ping us.

**Comment by clarkbw** [comment]
> Also, is there anyplace there's a complete public list of collaborators, &/or a way to notify the whole group @isaacs/collaborators - style?

No, that’s only visible in the settings and you need to be an admin for that tab. Also no way to notify this meta group, something that’s a good idea. 

I’m a collaborator as well.  I also work at GitHub. ✨

**Comment by aspiers** [comment]
Awesome to have you on board @clarkbw!

**Comment by TPS** [comment]
Welcome,  @ClarkBW!

@isaacs, other admins & all collaborators: Whaddy'all think of #792 & #1510, which are proposals for issue templates, containing policies, &c?

**Comment by TPS** [comment]
What happened to #459?

Also, should we do anything more w/ https://github.com/isaacs/github/community?

**Comment by TPS** [comment]
I'd also love a discussion/overhaul re: the 94 (!) labels in this repo: IMHO, too many are overly specific or vague, which makes it a bit of a Magic-8-Ball kinda choice to properly categorize issues.  I've done a little work w/ them, but some collaboration might be more effective.

**Comment by clarkbw** [comment]
Would be happy to audit the labels at some point. There are some names I’ve used like `render` which are internal to GitHub and need explanation to have meaning. I want the labels to be obvious and useful internally and externally.

**Comment by aspiers** [comment]
@TPS @clarkbw Brilliant idea to have a labels overhaul!  However it's off-topic for this issue, so I submitted #1549.  Let's track it there.

Regarding https://github.com/isaacs/github/community, again it's off-topic for this issue, but I suggest that we have one issue for each aspect which needs addressing:

- [ ] implementing a code of conduct
- [ ] adding a license (or at least deciding if we need one)
- [ ] creating an issue template (there's already #792 for this)
- [ ] creating a PR template

**Comment by TPS** [comment]
@aspiers How about adding to above list _(& then deleting this entire comment)_:
- [ ] policy re: [locking (especially, mega-) threads](https://github.com/isaacs/github/issues/283#issuecomment-499805736)

**Comment by aspiers** [comment]
@TPS Good idea re locking! - I've added it to the list, and updated my comment above about how to use the list.  I've also started filing more new issues.  Would prefer not to delete your comment as it makes the history harder for others to follow.
