### ISSUE TITLE
 Task list details only show on issue tracker if issue starts with checkboxes

### ISSUE THREAD

**Issue by ro-savage** [isaacs/github#650]
I am not sure if this is a new issue or I just never noticed before.

However, if you don't start an issue with a task list '- [ ]' then you don't get the talk lists counter on the issues page.

It seem to make sense to allow uses to make task lists without having to have the very first thing on the page a checkbox.

See images for examples: http://imgur.com/a/HYrTp

- [ ] This should create a task progress bar
- [ ] With 3 tasks
- [ ]  On this issue

**WORKS**
```
- [ ] Task 1
- [ ] Task 2
Random text
```

**DOESN'T WORK**
```
Random text
- [ ] Task 1
- [ ] Task 2
```

**Comment by ro-savage** [comment]
Attaching example images here

![screen shot 2016-04-15 at 12 42 05 pm](https://cloud.githubusercontent.com/assets/9244507/14548139/575bdd22-0308-11e6-969e-778166e8191c.png)

![screen shot 2016-04-15 at 12 42 15 pm](https://cloud.githubusercontent.com/assets/9244507/14548141/575d2178-0308-11e6-89f1-79da0ffac9b5.png)

![screen shot 2016-04-15 at 12 42 25 pm](https://cloud.githubusercontent.com/assets/9244507/14548140/575c3a42-0308-11e6-9726-9d73c6e5fa7d.png)

**Comment by NobbZ** [comment]
I have seen several issues that include a task list at the end and also have the
progressbar on the overview.

Have you tried to insert an extra blank line between text and the list?

```txt
This has no progressbar on the issues list
- [ ] I will never do this
- [X] But this is already finished
```

```txt
This should have a progressbar on the issues list

- [ ] I will never do this
- [X] But this is already finished
```

**Comment by ro-savage** [comment]
@NobbZ This doesn't make any difference for the github issues registers I have used. I have updated this issue too with a tasklist and no progress bar.

Github support have gotten back to me, to say it's a bug.

> Hi Ro,

> Sorry for the trouble! This is actually a bug on our end that the team is investigating -- intended behavior is for a task list to be tracked regardless of whether there is text before the list starts.

> Apologies again for the inconvenience with this, we'll update you when we have more information about a fix.

> Cheers, 
Alex

**Comment by TPS** [comment]
#637?

**Comment by ro-savage** [comment]
Yep same issue. I will close this issue.
