### ISSUE TITLE
Automatically check off task list items when referenced issue is closed

### ISSUE THREAD

**Issue by mumrah** [isaacs/github#654]
Perhaps when the list item text is _only_ a reference to another issue, it would be nice for the item to get checked off if the referenced issue was closed.

E.g., in issue `#1`

```
Some description

Sub-tasks:
- [ ] #2
- [ ] Do some other stuff
```

Issue `#2` gets closed, automatically update the body of issue `#1` to:

```
Some description

Sub-tasks:
- [x] #2
- [ ] Do some other stuff
```

This would be particularly nice for those of us wanting to track "Epics" with Github issues.

**Comment by skipjack** [comment]
I feel like I saw this work once a while back but I must've imagined it. Anyway, definitely would be a super-useful addition to their [task list](https://docs.github.com/en/github/managing-your-work-on-github/about-task-lists) feature. @mumrah on top of your example above, it would be nice to be able to add a short summary then link the issue at the end like so:

``` md
- [ ] Implement new loader (#4).
```

Even if we had to be more explicit (similar to the special `fixes` and `resolves` syntax in commits pr descriptions) it would still be useful imo:

``` md
- [ ] Implement new loader (resolved by #4).
```
